### ISSUE TITLE
Error whenever using a DT datatable

### ISSUE THREAD

**Issue by daattali** [rstudio/shinytest#69]
Using the following app:

```
library(shiny)

ui <- fluidPage(
  numericInput("num", "number", 5),
  DT::dataTableOutput("table")
)

server <- function(input, output, session) {
  output$table <- DT::renderDataTable({
    head(iris, input$num)
  })
}

shinyApp(ui = ui, server = server)
```

When I run `recordTest()`, change the input value to 6, and exit, I get this test script:

```
app <- ShinyDriver$new("..")
app$snapshotInit("mytests")

app$setInputs(table_rows_current = c(1, 2, 3, 4, 5))
app$setInputs(table_rows_all = c(1, 2, 3, 4, 5))
app$setInputs(num = 6)
app$setInputs(table_rows_current = character(0))
app$setInputs(table_rows_all = character(0))
app$setInputs(table_rows_current = c(1, 2, 3, 4, 5, 6))
app$setInputs(table_rows_all = c(1, 2, 3, 4, 5, 6))

app$snapshotCompare()
```

And the following error in the console:

```
Saved test code to C:\Users\Dean\Documents\R\test/tests/mytests.R
Saving baseline...
Error in session_makeRequest(self, private, endpoint, data, params, headers) : 
  Unable to find input binding for element
```

**Comment by wch** [comment]
I think this has been fixed -- there have been changes in how the recorded script gets generated. For example, if I do those actions with this test app, I get:

```R
app <- ShinyDriver$new("..")
app$snapshotInit("mytest")

# Input 'table_rows_selected' was set, but doesn't have an input binding.
# Input 'table_rows_current' was set, but doesn't have an input binding.
# Input 'table_rows_all' was set, but doesn't have an input binding.
# Input 'table_state' was set, but doesn't have an input binding.
# Input 'table_search' was set, but doesn't have an input binding.
# Input 'table_cell_clicked' was set, but doesn't have an input binding.
# Input 'table_rows_current' was set, but doesn't have an input binding.
# Input 'table_rows_all' was set, but doesn't have an input binding.
app$setInputs(num = 6)
# Input 'table_rows_current' was set, but doesn't have an input binding.
# Input 'table_rows_all' was set, but doesn't have an input binding.
# Input 'table_rows_current' was set, but doesn't have an input binding.
# Input 'table_rows_all' was set, but doesn't have an input binding.
app$snapshot()
```

And the script runs without error. However, for this particular app there is an issue with nonce values and session IDs, as mentioned in #107.

**Comment by bborgesr** [comment]
@wch That's true, but I just wanted to point out that besides the nonce and session ID, you still cannot interact with the DT widget in testing mode (search box, different pages, select rows, etc). (Which is obvious in the test scripts, since those lines are always comment out). That is documented in #105 though, so no need to discuss it here.
